Rework Caddyfile
searxng/searxng-docker pull request #255
Opened 2024-08-06 11:46 UTC by inetol

This PR completely reworks the Caddy config file to solve several inconveniences that are not worth having them in separate PRs, the changes are these...

* *Try* to protect the user data *(query searches, IPs and headers)* logged on Caddy if there is an error with the upstream response (or Caddy itself).
* Overwrite the `Cache-Control` and `Content-Security-Policy` headers if its matcher token *matches* rather than doing the comparison twice in a row.
* Prefer to set the ENV defaults directly in the Caddyfile.
* Modified the `Strict-Transport-Security` header to not include **all** subdomains in the HSTS policy nor mark the latter to enter the HSTS preload list.
* Modified the `Permissions-Policy` header to include/remove the new permissions that have been added in recent years.
* Remove the `encode` directive, otherwise Caddy will not passthrough the precompressed files served by uWSGI.
* Remove the `X-XSS-Protection` and `Feature-Policy` headers following the standards recommendations and evaluating the possible impact with older clients.
* Other minor structure and format changes.

All changes have been tested and validated without requiring major changes for users.

2025-01-03 09:38 UTC, unixfox commented on Caddyfile
> +{$SEARXNG_HOSTNAME:http://localhost}
Caddy is able to read from the .env file?

2025-01-03 14:00 UTC, inetol commented on Caddyfile
> +{$SEARXNG_HOSTNAME:http://localhost}
Yes, it also supports default value fallback https://caddyserver.com/docs/caddyfile/concepts#environment-variables

2025-01-03 14:06 UTC, inetol commented
I note as I almost forgot this PR existed, the default CSP is broken and forced you to use the image_proxy all the time, also some cache changes to try to reduce the number of requests to the server (specially /image_proxy)

2025-01-03 14:22 UTC, return42 commented
> I kinda wish SearXNG would handle that by itself instead of having to set the CSP ..

- :+1: --> https://github.com/searxng/searxng/issues/140

2025-02-14 09:26 UTC, unixfox requested changes

2025-02-14 09:26 UTC, unixfox commented on Caddyfile
> +			# Preserves fist 8 bits from IPv4 and 32 bits from IPv6
```suggestion
			# Preserves first 8 bits from IPv4 and 32 bits from IPv6
```

2025-02-14 09:27 UTC, unixfox approved these changes

2025-02-14 09:27 UTC, merged

2025-02-14 09:27 UTC, unixfox commented
Thanks for the PR :)